### ISSUE TITLE
Insert becomes small for no reason until something is typed

### ISSUE THREAD

**Issue by Moosems** [rdbende/tkcode#13]
Insert becomes small for no reason until something is typed

Video:

https://user-images.githubusercontent.com/95927277/178116022-23f9b86e-266b-4165-b37e-0d420d521f2d.mov

Json:
```json
        "general":
        {
            "background":{"$ref": "#/ColoringLight/bg"},
            "foreground": {"$ref": "#/ColoringLight/fg"},
            "insertbackground": "#c8894a",
            "insertwidth": 2,
            "highlightthickness": 0,
            "borderwidth": 0
        },
```

**Comment by rdbende** [comment]
It's a Tk bug, and it's somewhat intentional.

Since the insert cursor would cover the first letter at the edge of the widget, half of it is cut off to hide as little of the text as possible. This is clearly visible if you make the cursor a bit wider.
![image](https://user-images.githubusercontent.com/77941087/178119127-95fd490b-6786-4693-bcbd-440b14ec8e7d.png)

![image](https://user-images.githubusercontent.com/77941087/178119122-151158cf-0d8b-4861-aa8d-570f5b2d850a.png)

However, the bug here is that if you set padding or a wider border, the cursor is still cut off instead of drawing it on top of the padding, which is a bit odd.
![image](https://user-images.githubusercontent.com/77941087/178119129-0de99d66-221e-4be4-b710-ff5342f99360.png)

This bug has been fixed in the revised text widget implementation (which will be used in Tukaan): http://scidb.sourceforge.net/tk/insert-cursor.html

**Comment by Moosems** [comment]
So for now should I make it have an insertwidth of 1 to eliminate the issue?

**Comment by rdbende** [comment]
Yes, it's a solution.
